// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/app_settings.dart';
import 'data/models/memory_fact.dart';
import 'data/models/message.dart';
import 'data/models/mood_state.dart';
import 'data/models/persona_config.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1350341759699591298),
    name: 'AppSettings',
    lastPropertyId: const obx_int.IdUid(13, 6709580531882755079),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5951494993453566956),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5981516936745489600),
        name: 'ttsEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3355489328205059676),
        name: 'ttsAutoPlay',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3142537317428394312),
        name: 'notificationMorningEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6739626639594125326),
        name: 'notificationMorningTime',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2861864452468532432),
        name: 'notificationCheckinEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1038559318550111818),
        name: 'modelVariant',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6244975944666690606),
        name: 'isAgeVerified',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7909570167327583732),
        name: 'isOnboardingDone',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 165515503526454251),
        name: 'isPersonaSetup',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2064035449531545925),
        name: 'conversationSummary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 967219086682500198),
        name: 'themeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6709580531882755079),
        name: 'languageIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 652775646265387197),
    name: 'MemoryFact',
    lastPropertyId: const obx_int.IdUid(7, 4607935164879383317),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5943922320221182431),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1859302000144843362),
        name: 'key',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7242056929911849249),
        name: 'value',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 127071453946853270),
        name: 'sourceSnippet',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1644449446059291086),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1944899004224334314),
        name: 'lastReferencedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4607935164879383317),
        name: 'categoryIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4461514350763041745),
    name: 'Message',
    lastPropertyId: const obx_int.IdUid(6, 3781894061313651537),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4117000769873978623),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2606113049341228464),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6717205724508880273),
        name: 'isVoice',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5549793917685428431),
        name: 'mood',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5486096339294011554),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3781894061313651537),
        name: 'roleIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 1681218851533749567),
    name: 'MoodState',
    lastPropertyId: const obx_int.IdUid(5, 5259259496755635928),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2525625664663015003),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6147467560791500160),
        name: 'intensity',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2441961025983340281),
        name: 'lastUpdatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7239691196893597823),
        name: 'lastInteractionAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5259259496755635928),
        name: 'currentIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 4531824928226325680),
    name: 'PersonaConfig',
    lastPropertyId: const obx_int.IdUid(9, 2622669689795699599),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4925084284497469399),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6680708818558912691),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6896264915400620916),
        name: 'nicknameForUser',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7502621820046240674),
        name: 'avatarId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7624276163652642807),
        name: 'voiceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5222404844728441914),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8356063760909240275),
        name: 'genderIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7458515308193277673),
        name: 'personalityPresetIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2622669689795699599),
        name: 'hobbies',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 4531824928226325680),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AppSettings: obx_int.EntityDefinition<AppSettings>(
      model: _entities[0],
      toOneRelations: (AppSettings object) => [],
      toManyRelations: (AppSettings object) => {},
      getId: (AppSettings object) => object.id,
      setId: (AppSettings object, int id) {
        object.id = id;
      },
      objectToFB: (AppSettings object, fb.Builder fbb) {
        final notificationMorningTimeOffset = fbb.writeString(
          object.notificationMorningTime,
        );
        final modelVariantOffset = fbb.writeString(object.modelVariant);
        final conversationSummaryOffset = fbb.writeString(
          object.conversationSummary,
        );
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.ttsEnabled);
        fbb.addBool(2, object.ttsAutoPlay);
        fbb.addBool(3, object.notificationMorningEnabled);
        fbb.addOffset(4, notificationMorningTimeOffset);
        fbb.addBool(5, object.notificationCheckinEnabled);
        fbb.addOffset(6, modelVariantOffset);
        fbb.addBool(7, object.isAgeVerified);
        fbb.addBool(8, object.isOnboardingDone);
        fbb.addBool(9, object.isPersonaSetup);
        fbb.addOffset(10, conversationSummaryOffset);
        fbb.addInt64(11, object.themeIndex);
        fbb.addInt64(12, object.languageIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final ttsEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          6,
          false,
        );
        final ttsAutoPlayParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final notificationMorningEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final notificationMorningTimeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final notificationCheckinEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final modelVariantParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final isAgeVerifiedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final isOnboardingDoneParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final isPersonaSetupParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final conversationSummaryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final object =
            AppSettings(
                id: idParam,
                ttsEnabled: ttsEnabledParam,
                ttsAutoPlay: ttsAutoPlayParam,
                notificationMorningEnabled: notificationMorningEnabledParam,
                notificationMorningTime: notificationMorningTimeParam,
                notificationCheckinEnabled: notificationCheckinEnabledParam,
                modelVariant: modelVariantParam,
                isAgeVerified: isAgeVerifiedParam,
                isOnboardingDone: isOnboardingDoneParam,
                isPersonaSetup: isPersonaSetupParam,
                conversationSummary: conversationSummaryParam,
              )
              ..themeIndex = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                26,
                0,
              )
              ..languageIndex = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                28,
                0,
              );

        return object;
      },
    ),
    MemoryFact: obx_int.EntityDefinition<MemoryFact>(
      model: _entities[1],
      toOneRelations: (MemoryFact object) => [],
      toManyRelations: (MemoryFact object) => {},
      getId: (MemoryFact object) => object.id,
      setId: (MemoryFact object, int id) {
        object.id = id;
      },
      objectToFB: (MemoryFact object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final valueOffset = fbb.writeString(object.value);
        final sourceSnippetOffset = object.sourceSnippet == null
            ? null
            : fbb.writeString(object.sourceSnippet!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, valueOffset);
        fbb.addOffset(3, sourceSnippetOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.lastReferencedAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.categoryIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sourceSnippetParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final lastReferencedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object =
            MemoryFact(
                id: idParam,
                key: keyParam,
                value: valueParam,
                sourceSnippet: sourceSnippetParam,
                createdAt: createdAtParam,
                lastReferencedAt: lastReferencedAtParam,
              )
              ..categoryIndex = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                16,
                0,
              );

        return object;
      },
    ),
    Message: obx_int.EntityDefinition<Message>(
      model: _entities[2],
      toOneRelations: (Message object) => [],
      toManyRelations: (Message object) => {},
      getId: (Message object) => object.id,
      setId: (Message object, int id) {
        object.id = id;
      },
      objectToFB: (Message object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        final moodOffset = object.mood == null
            ? null
            : fbb.writeString(object.mood!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentOffset);
        fbb.addBool(2, object.isVoice);
        fbb.addOffset(3, moodOffset);
        fbb.addInt64(4, object.timestamp.millisecondsSinceEpoch);
        fbb.addInt64(5, object.roleIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final isVoiceParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final moodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object =
            Message(
                id: idParam,
                content: contentParam,
                timestamp: timestampParam,
                isVoice: isVoiceParam,
                mood: moodParam,
              )
              ..roleIndex = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                14,
                0,
              );

        return object;
      },
    ),
    MoodState: obx_int.EntityDefinition<MoodState>(
      model: _entities[3],
      toOneRelations: (MoodState object) => [],
      toManyRelations: (MoodState object) => {},
      getId: (MoodState object) => object.id,
      setId: (MoodState object, int id) {
        object.id = id;
      },
      objectToFB: (MoodState object, fb.Builder fbb) {
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.intensity);
        fbb.addInt64(2, object.lastUpdatedAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.lastInteractionAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.currentIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final intensityParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final lastUpdatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final lastInteractionAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object =
            MoodState(
                id: idParam,
                intensity: intensityParam,
                lastUpdatedAt: lastUpdatedAtParam,
                lastInteractionAt: lastInteractionAtParam,
              )
              ..currentIndex = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                12,
                0,
              );

        return object;
      },
    ),
    PersonaConfig: obx_int.EntityDefinition<PersonaConfig>(
      model: _entities[4],
      toOneRelations: (PersonaConfig object) => [],
      toManyRelations: (PersonaConfig object) => {},
      getId: (PersonaConfig object) => object.id,
      setId: (PersonaConfig object, int id) {
        object.id = id;
      },
      objectToFB: (PersonaConfig object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final nicknameForUserOffset = fbb.writeString(object.nicknameForUser);
        final avatarIdOffset = fbb.writeString(object.avatarId);
        final voiceIdOffset = fbb.writeString(object.voiceId);
        final hobbiesOffset = fbb.writeList(
          object.hobbies.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, nicknameForUserOffset);
        fbb.addOffset(3, avatarIdOffset);
        fbb.addOffset(4, voiceIdOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.genderIndex);
        fbb.addInt64(7, object.personalityPresetIndex);
        fbb.addOffset(8, hobbiesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final hobbiesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 20, []);
        final nicknameForUserParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final avatarIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final voiceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object =
            PersonaConfig(
                id: idParam,
                name: nameParam,
                hobbies: hobbiesParam,
                nicknameForUser: nicknameForUserParam,
                avatarId: avatarIdParam,
                voiceId: voiceIdParam,
                createdAt: createdAtParam,
              )
              ..genderIndex = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                16,
                0,
              )
              ..personalityPresetIndex = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                18,
                0,
              );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppSettings] entity fields to define ObjectBox queries.
class AppSettings_ {
  /// See [AppSettings.id].
  static final id = obx.QueryIntegerProperty<AppSettings>(
    _entities[0].properties[0],
  );

  /// See [AppSettings.ttsEnabled].
  static final ttsEnabled = obx.QueryBooleanProperty<AppSettings>(
    _entities[0].properties[1],
  );

  /// See [AppSettings.ttsAutoPlay].
  static final ttsAutoPlay = obx.QueryBooleanProperty<AppSettings>(
    _entities[0].properties[2],
  );

  /// See [AppSettings.notificationMorningEnabled].
  static final notificationMorningEnabled =
      obx.QueryBooleanProperty<AppSettings>(_entities[0].properties[3]);

  /// See [AppSettings.notificationMorningTime].
  static final notificationMorningTime = obx.QueryStringProperty<AppSettings>(
    _entities[0].properties[4],
  );

  /// See [AppSettings.notificationCheckinEnabled].
  static final notificationCheckinEnabled =
      obx.QueryBooleanProperty<AppSettings>(_entities[0].properties[5]);

  /// See [AppSettings.modelVariant].
  static final modelVariant = obx.QueryStringProperty<AppSettings>(
    _entities[0].properties[6],
  );

  /// See [AppSettings.isAgeVerified].
  static final isAgeVerified = obx.QueryBooleanProperty<AppSettings>(
    _entities[0].properties[7],
  );

  /// See [AppSettings.isOnboardingDone].
  static final isOnboardingDone = obx.QueryBooleanProperty<AppSettings>(
    _entities[0].properties[8],
  );

  /// See [AppSettings.isPersonaSetup].
  static final isPersonaSetup = obx.QueryBooleanProperty<AppSettings>(
    _entities[0].properties[9],
  );

  /// See [AppSettings.conversationSummary].
  static final conversationSummary = obx.QueryStringProperty<AppSettings>(
    _entities[0].properties[10],
  );

  /// See [AppSettings.themeIndex].
  static final themeIndex = obx.QueryIntegerProperty<AppSettings>(
    _entities[0].properties[11],
  );

  /// See [AppSettings.languageIndex].
  static final languageIndex = obx.QueryIntegerProperty<AppSettings>(
    _entities[0].properties[12],
  );
}

/// [MemoryFact] entity fields to define ObjectBox queries.
class MemoryFact_ {
  /// See [MemoryFact.id].
  static final id = obx.QueryIntegerProperty<MemoryFact>(
    _entities[1].properties[0],
  );

  /// See [MemoryFact.key].
  static final key = obx.QueryStringProperty<MemoryFact>(
    _entities[1].properties[1],
  );

  /// See [MemoryFact.value].
  static final value = obx.QueryStringProperty<MemoryFact>(
    _entities[1].properties[2],
  );

  /// See [MemoryFact.sourceSnippet].
  static final sourceSnippet = obx.QueryStringProperty<MemoryFact>(
    _entities[1].properties[3],
  );

  /// See [MemoryFact.createdAt].
  static final createdAt = obx.QueryDateProperty<MemoryFact>(
    _entities[1].properties[4],
  );

  /// See [MemoryFact.lastReferencedAt].
  static final lastReferencedAt = obx.QueryDateProperty<MemoryFact>(
    _entities[1].properties[5],
  );

  /// See [MemoryFact.categoryIndex].
  static final categoryIndex = obx.QueryIntegerProperty<MemoryFact>(
    _entities[1].properties[6],
  );
}

/// [Message] entity fields to define ObjectBox queries.
class Message_ {
  /// See [Message.id].
  static final id = obx.QueryIntegerProperty<Message>(
    _entities[2].properties[0],
  );

  /// See [Message.content].
  static final content = obx.QueryStringProperty<Message>(
    _entities[2].properties[1],
  );

  /// See [Message.isVoice].
  static final isVoice = obx.QueryBooleanProperty<Message>(
    _entities[2].properties[2],
  );

  /// See [Message.mood].
  static final mood = obx.QueryStringProperty<Message>(
    _entities[2].properties[3],
  );

  /// See [Message.timestamp].
  static final timestamp = obx.QueryDateProperty<Message>(
    _entities[2].properties[4],
  );

  /// See [Message.roleIndex].
  static final roleIndex = obx.QueryIntegerProperty<Message>(
    _entities[2].properties[5],
  );
}

/// [MoodState] entity fields to define ObjectBox queries.
class MoodState_ {
  /// See [MoodState.id].
  static final id = obx.QueryIntegerProperty<MoodState>(
    _entities[3].properties[0],
  );

  /// See [MoodState.intensity].
  static final intensity = obx.QueryDoubleProperty<MoodState>(
    _entities[3].properties[1],
  );

  /// See [MoodState.lastUpdatedAt].
  static final lastUpdatedAt = obx.QueryDateProperty<MoodState>(
    _entities[3].properties[2],
  );

  /// See [MoodState.lastInteractionAt].
  static final lastInteractionAt = obx.QueryDateProperty<MoodState>(
    _entities[3].properties[3],
  );

  /// See [MoodState.currentIndex].
  static final currentIndex = obx.QueryIntegerProperty<MoodState>(
    _entities[3].properties[4],
  );
}

/// [PersonaConfig] entity fields to define ObjectBox queries.
class PersonaConfig_ {
  /// See [PersonaConfig.id].
  static final id = obx.QueryIntegerProperty<PersonaConfig>(
    _entities[4].properties[0],
  );

  /// See [PersonaConfig.name].
  static final name = obx.QueryStringProperty<PersonaConfig>(
    _entities[4].properties[1],
  );

  /// See [PersonaConfig.nicknameForUser].
  static final nicknameForUser = obx.QueryStringProperty<PersonaConfig>(
    _entities[4].properties[2],
  );

  /// See [PersonaConfig.avatarId].
  static final avatarId = obx.QueryStringProperty<PersonaConfig>(
    _entities[4].properties[3],
  );

  /// See [PersonaConfig.voiceId].
  static final voiceId = obx.QueryStringProperty<PersonaConfig>(
    _entities[4].properties[4],
  );

  /// See [PersonaConfig.createdAt].
  static final createdAt = obx.QueryDateProperty<PersonaConfig>(
    _entities[4].properties[5],
  );

  /// See [PersonaConfig.genderIndex].
  static final genderIndex = obx.QueryIntegerProperty<PersonaConfig>(
    _entities[4].properties[6],
  );

  /// See [PersonaConfig.personalityPresetIndex].
  static final personalityPresetIndex = obx.QueryIntegerProperty<PersonaConfig>(
    _entities[4].properties[7],
  );

  /// See [PersonaConfig.hobbies].
  static final hobbies = obx.QueryStringVectorProperty<PersonaConfig>(
    _entities[4].properties[8],
  );
}
